### PR TITLE
Use `preloaded` from `-sbt-dir`

### PR DESCRIPTION
**Pull request by liff**
Fixes sbt/sbt#3598.

### CODE REVIEW

**Comment by liff** [comment]
On further reflection, I think the launcher should also try to figure out if `-Dsbt.global.base` and/or`-Dsbt.preloaded` are defined via some other mechanism.

**Comment by eed3si9n** [comment]
Could you rebase please? I just merged https://github.com/sbt/sbt-launcher-package/pull/240

**Comment by eed3si9n** [comment]
When I run without `-sbt-dir` it's creating `local-preloaded` on the current directory.

**Comment by eed3si9n** [comment]
I don't have time to debug what's going on, so I am going to revert the commits from this PR.

**Pull request merged**
