### PR TITLE
[WIP] Handle SBT_OPTS in bash

### PR DESCRIPTION
**Pull request by iwamatsu0430**
Fixes https://github.com/sbt/sbt/issues/4193

### CODE REVIEW

**Comment by eed3si9n** [comment]
@iwamatsu0430 Thanks! Could you add `-no-colors` here? - https://github.com/sbt/sbt-launcher-package/blob/master/citest/test.sh#L20

**Comment by nafg** [comment]
When will this be merged?

Seems like updating the CI script should be a separate PR.

**Comment by eed3si9n** [comment]
I guess you're right.

**Comment by eed3si9n** [comment]
```
$ export SBT_OPTS="-Xms2048M -Xmx2048M -Xss2M -XX:MaxPermSize=512M"
$ sbt
....
[error] Expected symbol
[error] Not a valid command: -
[error] Expected end of input.
[error] Expected '--'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] -Xms2048M
[error]  ^
```

I need to revert this PR.

**Comment by nafg** [comment]
I thought that was the issue this PR solves?

**Comment by nafg** [comment]
Actually shouldn't that either be JAVA_OPTS or have -J in front of each
option?

**Comment by eed3si9n** [comment]
I've been using `SBT_OPTS` like `JAVA_OPTS`, I guess.
Adding `-J` didn't help, and changes like this should maintain backward compatibility if possible.

**Comment by jeffrey-aguilera** [comment]
Neither SBT_OPTS or .sbtopts works in 1.2.7.

**Pull request merged**
