### PR TITLE
Add simple sbt new test

### PR DESCRIPTION
**Pull request by er1c**

### CODE REVIEW

**Comment by er1c** [comment]
Something appears to be broken on windows with the sbt new...I just reproduced this locally as well :/

Triggered by:

```
[error] java.io.IOException: Unable to delete file: C:\Users\travis\AppData\Local\Temp\giter8-755208374300\src\main\g8\.gitignore
```

Full Stack Trace:

```
[error] java.io.IOException: Unable to delete file: C:\Users\travis\AppData\Local\Temp\giter8-755208374300\src\main\g8\.gitignore
[error] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400)
[error] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error] 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error] 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error] 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error] 	at giter8.JgitHelper.cleanup(JgitHelper.scala:58)
[error] 	at giter8.Giter8.run(giter8.scala:46)
[error] 	at giter8.Giter8.run(giter8.scala:56)
[error] 	at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:30)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.TemplateCommandUtil$.call(TemplateCommandUtil.scala:121)
[error] 	at sbt.TemplateCommandUtil$.runTemplate(TemplateCommandUtil.scala:96)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$run$1(TemplateCommandUtil.scala:72)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$run$1$adapted(TemplateCommandUtil.scala:68)
[error] 	at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:115)
[error] 	at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:112)
[error] 	at scala.collection.immutable.List.find(List.scala:89)
[error] 	at sbt.TemplateCommandUtil$.run(TemplateCommandUtil.scala:68)
[error] 	at sbt.TemplateCommandUtil$.runTemplate(TemplateCommandUtil.scala:55)
[error] 	at sbt.TemplateCommandUtil$.$anonfun$templateCommand$2(TemplateCommandUtil.scala:25)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:144)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:139)
[error] 	at sbt.Command$.process(Command.scala:183)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$1(MainLoop.scala:150)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:162)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:150)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:138)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:269)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:273)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:138)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:138)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:131)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:109)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:103)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:58)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:43)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:173)
[error] 	at sbt.xMainImpl$.run(Main.scala:126)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.xMain.run(Main.scala:55)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.IOException: Unable to delete file: C:\Users\travis\AppData\Local\Temp\giter8-755208374300\src\main\g8\.gitignore
[error] Use 'last' for the full log.
- sbt new scala/scala-seed.g8 --name=template-test should create a new seed project *** FAILED ***
  AssertionError: 
  
  assert(out == 0)
         |   |
         1   false
    com.eed3si9n.expecty.Expecty$ExpectyListener.expressionRecorded(Expecty.scala:25)
    com.eed3si9n.expecty.RecorderRuntime.recordExpression(RecorderRuntime.scala:34)
    example.test.SbtRunnerTest$.$anonfun$new$18(RunnerTest.scala:144)
    minitest.SimpleTestSuite.$anonfun$test$1(SimpleTestSuite.scala:27)
    minitest.api.TestSpec$.$anonfun$sync$1(TestSpec.scala:51)
    minitest.api.TestSpec.apply(TestSpec.scala:27)
    minitest.api.Properties.$anonfun$iterator$2(Properties.scala:38)
    minitest.api.TestSpec.apply(TestSpec.scala:27)
    minitest.runner.Task.loop$1(Task.scala:56)
    minitest.runner.Task.$anonfun$execute$1(Task.scala:63)
    scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
    scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Error: Total 16, Failed 0, Errors 1, Passed 15, Canceled 2
[error] Error during tests:
[error] 	example.test.SbtRunnerTest
[error] (integrationTest/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 485 s, completed Oct 19, 2019 7:07:16 PM
The command "sbt -Dsbt.build.version=$SBT_VER universal:packageBin universal:stage integrationTest/test" exited with 1.
0.04s$ cd citest
```

**Comment by er1c** [comment]
Related: https://github.com/playframework/play-scala-seed.g8/issues/56

**Comment by er1c** [comment]
I added a bug for giter8 here: https://github.com/foundweekends/giter8/issues/439 with my speculation on the issue.

**Comment by eed3si9n** [comment]
Moved the runner to sbt/sbt

**Pull request closed without merging**
